# Pricing Engine Configuration

# Price ladder configuration
price_ladder:
  type: "x.99"  # Every digit minus 1 øre
  max_price: 2000  # Max price in NOK

# Price change constraints
price_change:
  min_pct: -10  # Minimum price change percentage
  max_pct: 10   # Maximum price change percentage

# Supabase configuration
supabase:
  url: "YOUR_SUPABASE_URL"
  key: "YOUR_SUPABASE_API_KEY"
  tables:
    products: "products"
    item_groups: "item_groups"
    item_group_members: "item_group_members"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"